if(SYCL_IMPL STREQUAL "IntelDPCPP")
  find_program(ICPX_EXECUTABLE icpx)
  if(ICPX_EXECUTABLE)
    set(CMAKE_C_COMPILER "icx" CACHE PATH "C compiler")
    set(CMAKE_CXX_COMPILER "icpx" CACHE PATH "C++ compiler")
  else()
    set(CMAKE_C_COMPILER "clang" CACHE PATH "C compiler")
    set(CMAKE_CXX_COMPILER "clang++" CACHE PATH "C++ compiler")
  endif()
elseif(SYCL_IMPL STREQUAL "AdaptiveCpp")
  if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER "acpp" CACHE PATH "C++ compiler")
  endif()
endif()
